### ISSUE TITLE
Story

### ISSUE THREAD

**Issue by Alexander-Minascurta** [Nikolai-Repin/Hellscent#24]
Get the story done and made before 11/07.

**Comment by Alexander-Minascurta** [comment]
**Hellsent Story**
**Theme:** 9 circles of hell
**How it is conveyed nonstory wise**: as we go furth down each level or floor the palette changes so that it shows the decent
Hero is a Knight who is diving down into the circles of hell in order to prevent monsters from kidnapping and hurting the worlds people.
Notes will be left for the hero to find of enemy’s and prisoners.
**Story:**
Through Recent years monsters and demons have spread throughout the world, kidnapping, killing and pillaging towns turning the remaining land into a burning hellish landscape. Now a hero who is unnamed has taken it upon him/herself to go and rid the world of these demons and undead monsters. He has fought his way through the burnt hellscape of land that was laid to waste and has begun is journey down into the circles of hell to defeat the high demons of circle and close the rift that allowed for demons and undead to pour out.

**Comment by Alexander-Minascurta** [comment]
Also I created a name

**Comment by aknotwell** [comment]
Do we any ideas of what we would like as an Intro? I can't imagine we would have an actual animation, unless we have time. Maybe something along the lines of Star Wars with the scrolling text?
