### ISSUE TITLE
Player is able to move while dungeon is still generating

### ISSUE THREAD

**Issue by LemoCoffee** [Nikolai-Repin/Hellscent#46]
We need some sort of loading screen so the player can't see the unfinished level

**Comment by aknotwell** [comment]
Will the player be able to move even if the level is still generating? Like they can still use the WASD keys, even if they can't see the screen.

**Comment by LemoCoffee** [comment]
Added code to disable player input while dungeon is generating, and I believe Nikolai got the loading screen done earlier today
